### ISSUE TITLE
MINSWAN for iOS

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/blog#105]
:warning: INCOMING SHOWER THOUGHTS :warning:

So the Ruby community has this expression called [MINSWAN](http://blog.steveklabnik.com/posts/2011-08-19-matz-is-nice-so-we-are-nice): Matz is nice so we are nice. That's worked well since the ruby community was started by this one, nice person. 

But iOS doesn't have this person, so we can't really have something analogous. 

Except, there are a tonne of ruby people who started in the community and acted nice, even if they didn't know who Matz was. Why? Because everyone else was nice. 

iOS doesn't need MINSWAN, we need something like "*everyone* else is nice so I am nice" – but first, we need everyone to be nice. 

Are we there yet? No, but we're close. A noticeable shift has occurred in the past year or so, coinciding with Swift's announcement and an explosion in OSS participation. 

This ideal can be reached, but it needs a critical mass of iOS developers to do two things:

1. Give honest, constructive feedback when someone is being unnecessarily negative.
1. Graciously accept feedback that we receive and reflect on it. 

Negativity happens! But ideally, it doesn't spread, and it's not the norm. 

Consider the following best-case-scenario:

Bob: "I don't like X because it's stupid. Anyone who uses X is stupid, too."
Carol: "That's not very kind, Bob."

![](http://www.doctornerdlove.com/wp-content/uploads/2012/04/young-neil-scott-pilgrim.jpg)

What does Bob do now? He can accept Carol's feedback and become a nicer person, or he can ignore her and keep being an asshole. At that point, Carol has a decision to make: is Bob someone she wants to follow? Is he worth paying attention to?

If someone doesn't respond by behaving better, you can mute them or unfollow them. It's really for your own good: 

https://twitter.com/chriseidhof/status/624158166830477312
https://twitter.com/bontoJR/status/624207699090231297

Friction gets followers, but only because we let it.

----------------

This post might be germane: http://breakthesystem.org/ash-furrow-on-positivity

I'd like to get feedback on this – I think the idea but it needs to be flushed out. Maybe more supporting evidence. Thoughts @orta @chriseidhof @bontojr ?

**Comment by chriseidhof** [comment]
I think it sounds like a great idea to promote this. I hope it'll have a positive impact! I wonder if you can prove it. I think it could work for small problems! It's not going to solve all our issues, but that's okay =).

**Comment by ashfurrow** [comment]
Thanks Chris! I'm going to sleep on it and refine it over the next few days. 

Small steps :)

**Comment by bontoJR** [comment]
Few months ago I would definitely say, probably  naively, that this would not have been necessary, but now I truly believe it is.

I see there's a problem, it's not at the same level of [functional programmers being appointed as arrogant](http://www.devjoy.com/2015/07/some-functional-programmers-are-arrogant/) once a month, but it's better to face it now before having people complaining the iOS/Mac/Swift community is full of arrogants and negative people.

I think it's mostly about confrontation. In your example there's no room to have a healty discussion, that is the most fundamental part in a programmer's life. A programmer that is not able to communicate will always be an island. Being technically prepared would make you a top programmer, but if you don't know how to communicate nobody will ever want to work with you. Negativity here counts, somebody always negative will kill teams' (or community's) positive attitude, maybe even destroying a valid project.

I would also like to have an opinion about developers with a certain reputation, or being widely recognized as "ambassadors" of a certain community, behaving badly against other projects publicly, implicitly discouraging other people in trying the targeted project, instead of maybe having a private chat with the counterpart involved if something is not fine with it.

**Comment by ashfurrow** [comment]
Another good "positive" tweet: https://twitter.com/tenderlove/status/624628255459377152

Instead of yelling or shouting or swearing, Aaron looks on the bright side. Aw yeah.

**Comment by ashfurrow** [comment]
Ashley brought up this counterpoint-ish thing: http://everydayfeminism.com/2015/04/lies-about-negative-people/
