### ISSUE TITLE
Code as Art in an engineering setting

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/blog#188]
I've been thinking about [this](https://twitter.com/keshyart/status/689203349900546048) in the context of the "code is art" school of thought. Like, art can be critiqued but it can't be _wrong_, but code can _definitely_ be wrong. It can even be objectively bad, which I'm not sure art can. 

But the thing is, most developers got into coding because it was _fun_, but as professionals we mostly only care if our code is correct and effective and stuff. What do we lose when we only focus on those metrics? What do we gain? I'm not sure. Need to think on it some more, maybe get some input from @orta. Definitely is at odds with the "engineer" label we seem to have hoisted on ourselves, a term I'm growing more and more uncomfortable using.

Also, speaking of Mr Rogers, it'd be :100: to reference this somehow: https://medium.com/inconvenient-and-unreasonable/lessons-from-mr-rogers-23b8548353c8

**Comment by orta** [comment]
Would recommend some study of `_why` - https://vimeo.com/103600757

Was the pinnacle of code as art, when he disappeared there was a lot of talk about it
https://www.smashingmagazine.com/2010/05/why-a-tale-of-a-post-modern-genius/
http://ejohn.org/blog/eulogy-to-_why/
http://words.steveklabnik.com/closure

Important sidenote: `_why` wrote code that was really hard to others to work wth in his absence though, https://news.ycombinator.com/item?id=4976378

**Comment by orta** [comment]
_Code as Art is_ hard because Art is generally something that isn't directly useful other than to evoke an idea. Code generally has a specific end goal in mind.

> But the thing is, most developers got into coding because it was fun, but as professionals we mostly only care if our code is correct and effective and stuff

These are the things that make ruby a more fun language for me to work in than Swift still. Could you imagine the swift compiler allowing something as redundant as `unless not x > 9 and y < 5 { puts "hi" }`. 

Programming is a social activity though, and in order to work well with others we have to do things like processes and unit tests, in order to ensure that we meet the teams goals. There's probably no-one relying on a piece of video-art like an iOS developer relies on CocoaPods in order to make a living.

**Comment by orta** [comment]
just a small brain dump

**Comment by ashfurrow** [comment]
Cleaning up issues – I don't think I'm ever going to get to this, so I'm going to close.
