### ISSUE TITLE
Search is inconsistent

### ISSUE THREAD

**Issue by NobinPegasus** [ashfurrow/blog#512]
The search you implemented is inconsistent.
Like here if we search new we get everything that has a keyword new in them.
![image](https://user-images.githubusercontent.com/56520367/236306638-8a0e83d9-d5a0-435d-9afc-ce9b7296ed79.png)

But if we search using Got. Same goes for many  other words like What, How, At and many more.
![image](https://user-images.githubusercontent.com/56520367/236306638-8a0e83d9-d5a0-435d-9afc-ce9b7296ed79.png)
I'm not sure why is it behaving like this

**Comment by NobinPegasus** [comment]
![image](https://user-images.githubusercontent.com/56520367/236308998-2e8b73ce-49e2-4f47-b47e-82db2d07791a.png)

**Comment by ashfurrow** [comment]
The site's search is powered by [Elasticlunr.js](http://elasticlunr.com/), a client-side search index and engine. This means that the entire search index, for every blog post, as to be downloaded to the browser to perform searches. There is a trade-off between consistent results for common words and keeping the index size small, similar to the tradeoff with [stop words](https://en.wikipedia.org/wiki/Stop_word). I can't say for sure exactly why this is happening because I haven't dived into the Elasticlunr.js implementation, but I would imagine it has something to do with how often words occur in the corpus. "new" appears on my blog over twice as many time as "got", which is why I think only it gets indexed.
